#!/usr/bin/env python3
#
# Copyright (c) 2016 Romain Bignon
#               All Rights Reserved
#
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

from clitodb.main import CLItoDB

if __name__ == '__main__':
    try:
        CLItoDB().cmdloop()
    except (KeyboardInterrupt,EOFError):
        print('')
